version: "3.7"

services:
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints: [node.hostname == node-docker-1]
    volumes:
      - pgdata:/bitnami/postgresql
    env_file: .env
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.12
    ports:
      - "4369:4369"
      - "5551:5551"
      - "5552:5552"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    env_file: .env
    volumes:
      - "rabbitmq_data:/bitnami/rabbitmq/mnesia"
volumes:
  pgdata:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
